# Basic Project - Makefile

.PHONY: test test-all test-step-00 test-step-01 test-step-02 test-step-03

RACKET := racket

test: test-all

test-all: test-step-00 test-step-01 test-step-02 test-step-03

test-step-00:
	@echo "\n=== basic/step-00 ===" && $(RACKET) step-00/exercise.scm

test-step-01:
	@echo "\n=== basic/step-01 ===" && $(RACKET) step-01/exercise.scm

test-step-02:
	@echo "\n=== basic/step-02 ===" && $(RACKET) step-02/exercise.scm

test-step-03:
	@echo "\n=== basic/step-03 ===" && $(RACKET) step-03/exercise.scm


